jobs:
  build-then-run-tests:
    env:
      MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
    name: Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '8'
    - continue-on-error: true
      name: Cache dependencies
      uses: actions/cache@v4
      with:
        key: ${{matrix.modules.name}}-gaffer-dependencies
        path: '~/.m2/repository

          !~/.m2/repository/uk

          '
        restore-keys: ${{matrix.modules.name}}
    - continue-on-error: true
      name: Install
      run: mvn -B -ntp clean install -P quick -Dlegacy=true -pl ${{matrix.modules.values}}
        -am
    - continue-on-error: true
      name: Test
      run: mvn -B -ntp verify -P coverage -Dlegacy=true -pl ${{matrix.modules.values}}
    strategy:
      fail-fast: true
      matrix:
        modules:
        - name: Core
          values: :gaffer2,:core,:access,:cache,:common-util,:data,:exception,:graph,:operation,:serialisation,:store,:type
        - name: Accumulo
          values: :accumulo-store,:accumulo-rest
        - name: Federated-And-Map
          values: :integration-test,:federated-store,:map-store,:map-rest
        - name: REST
          values: :rest-api,:common-rest,:spring-rest,:core-rest,:store-implementation,:proxy-store
        - name: Examples
          values: :example,:basic,:basic-model,:basic-rest,:road-traffic,:road-traffic-model,:road-traffic-generators,:road-traffic-rest,:road-traffic-demo,:federated-demo
        - name: Big-Data-Libraries
          values: :flink-library,:hdfs-library,:spark,:spark-library,:spark-accumulo-library
        - name: Time-Library
          values: :library,:time-library
        - name: Caches
          values: :cache-library,:sketches-library,:bitmap-library,:hazelcast-cache-service,:jcs-cache-service
name: Continuous Integration (Legacy)
on:
  repository_dispatch:
    types: trigger-ga___continuous-integration-legacy.yaml
