jobs:
  issue-links:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: tkt-actions/add-issue-links@v1.8.2
      with:
        branch-prefix: gh-
        link-style: body
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        resolve: 'true'
name: Issue Links
on:
  repository_dispatch:
    types: trigger-ga___link-issue.yml
