jobs:
  run-maven-release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '8'
    - continue-on-error: true
      name: Checkout Branch
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        CODE_SIGNING_IV: ${{ secrets.CODE_SIGNING_IV }}
        CODE_SIGNING_KEY: ${{ secrets.CODE_SIGNING_KEY }}
      name: Decode CodeSigning key
      run: openssl aes-256-cbc -K "$CODE_SIGNING_KEY" -iv "$CODE_SIGNING_IV" -in cd/codesigning.asc.enc
        -out cd/codesigning.asc -d
    - continue-on-error: true
      name: Import CodeSigning key
      run: gpg --batch --fast-import cd/codesigning.asc
    - continue-on-error: true
      env:
        GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSS_NEXUS_PASSWORD: ${{ secrets.OSS_NEXUS_PASSWORD }}
        OSS_NEXUS_USERNAME: ${{ secrets.OSS_NEXUS_USERNAME }}
      name: Release to Nexus
      run: mvn deploy -P quick,ossrh-release --settings cd/mvnsettings.xml -B
name: Release To Nexus as standalone
on:
  repository_dispatch:
    types: trigger-ga___release-standalone.yaml
