jobs:
  update-koryphe-version:
    env:
      MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
      VERSION_UPDATE_BRANCH: update-koryphe-version-${{ github.event.inputs.version
        }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout branch
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
    - continue-on-error: true
      name: Set up Github credentials
      run: 'git config user.name github-actions[bot]

        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

        '
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '8'
    - continue-on-error: true
      name: Update Korpyhe Version
      run: ./cd/updateKorypheVersion.sh ${{ github.event.inputs.version }}
    - continue-on-error: true
      if: ${{ success() }}
      name: Submit PR
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: ${{ env.SOURCE_BRANCH }}
        github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        pr_body: Automated GitHub Actions PR to upgrade to version ${{ github.event.inputs.version
          }} of Koryphe
        pr_title: Update Koryphe version to ${{ github.event.inputs.version }}
        source_branch: ${{ env.VERSION_UPDATE_BRANCH }}
name: Update Korpyhe Version
on:
  repository_dispatch:
    types: trigger-ga___update-koryphe-version.yaml
